---
title: "main.rmd"
author: "Poppy Stanton"
date: "17/11/2020"
output: bookdown:: html_document: default
        bookdown:: pdf_document: default
        bookdown:: word_document: default 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      fig.retina = 3)
```

```{r package_loading}
library(tidyverse)
```

# Intrduction
Data on male and female chaffinches is analyzed  


# Methods
Packages from the Tidyverse are used in the formatting and analysis of chaff data 

### Importing and tidying the data

```{r data_tidying}

chaff <- read.table("data_raw/chaff.txt", header = TRUE)

chaff2 <- chaff %>%
  pivot_longer(names_to = "Sex",
               values_to = "Mass",
               cols = everything())

```

### Creating a function to calculate SS(x)

```{r function}
sum_sq <- function(df, measure){
  df %>% summarise_(ss = sum(({{measure}} - mean({{measure}}))^2))
}
sum_sq(chaff2, chaff2$Mass)
```


Now including sex as a variable in the function 

```{r function}
sum_sq <- function(df, measure, group){
  df %>% group_by({{ group}}) %>%
    summarise(ss = sum(({{measure}} - mean({{measure}}))^2))
}

```







# Results



# Discussion 










